### ISSUE TITLE
The download speed is too slow?

### ISSUE THREAD

**Issue by tqvinhcs** [epic-kitchens/download-scripts#2]
Hi I have try the download scripts. 
However, the speed is too slow only ~700 KB/s. 
Given the rgb and frame is 200GB + 96 GB, it may weeks to finish with one go scripts.
I have try with multiple files download but the connection is always be broken.
Do you have any solution for this?

**Comment by willprice** [comment]
The data.bris team have recently increased their server capacity so downloads should be a bit faster.
