### ISSUE TITLE
Readme Issue

### ISSUE THREAD

**Issue by ElegantLin** [epic-kitchens/download-scripts#3]
> If you do not specify any parameter, the scripts will assume the output path is`~/Download`

It should be `~/Downloads`, I think.

Thanks

**Comment by dmoltisanti** [comment]
Hi, thanks for pointing that out. That's actually already the case, the script will assume the path is `~/Downloads`. It was just a spelling issue in the read me, which has been updated :) 

Closing this,

Thanks
