### ISSUE TITLE
SSL Error, Cant Download Dataset

### ISSUE THREAD

**Issue by sawyermade** [epic-kitchens/download-scripts#4]
wget http://data.bris.ac.uk/datasets/3h91syskeag572hl6tvuovwv4d/videos/test/P01/P01_11.MP4 
--2020-05-22 11:07:52--  http://data.bris.ac.uk/datasets/3h91syskeag572hl6tvuovwv4d/videos/test/P01/P01_11.MP4

Resolving data.bris.ac.uk (data.bris.ac.uk)... 137.222.0.78
Connecting to data.bris.ac.uk (data.bris.ac.uk)|137.222.0.78|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://data.bris.ac.uk/datasets/3h91syskeag572hl6tvuovwv4d/videos/test/P01/P01_11.MP4 [following]
--2020-05-22 11:07:53--  https://data.bris.ac.uk/datasets/3h91syskeag572hl6tvuovwv4d/videos/test/P01/P01_11.MP4
Connecting to data.bris.ac.uk (data.bris.ac.uk)|137.222.0.78|:443... connected.
OpenSSL: error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small
Unable to establish SSL connection.

# Info
Ubuntu 20.04
OpenSSL 1.1.1f  31 Mar 2020

**Comment by dmoltisanti** [comment]
Hi, do you still have this issue? I just tried 

`wget http://data.bris.ac.uk/datasets/3h91syskeag572hl6tvuovwv4d/videos/test/P01/P01_11.MP4`

and it works fine for me.

Also, what script caused the issue?

**Comment by sawyermade** [comment]
I was able to get it working by altering the default DNE key security from level 2 to level 1 for OpenSSL on Ubuntu 20.04. Without doing that, it would not work. Are you using 20.04?

**Comment by dmoltisanti** [comment]
I am using Fedora 32. I'm going to close this issue since you managed to fix the issue.

Thanks for sharing the solution!
