### ISSUE TITLE
Frame Extraction Specification

### ISSUE THREAD

**Issue by b0ku1** [epic-kitchens/download-scripts#5]
Hi there, due to the slow downloading speed, we would love to just download the frames. Based on a preliminary check on test/P01, seems like the rgb frames are extracted at 59.94 fps.

However, according to the paper: 
Before each recording, the participants checked the battery life and viewpoint,

> using the GoPro Capture app, so that their stretched hands were approximately
> located at the middle of the camera frame. The camera was set to linear field
> of view, 59.94fps and Full HD resolution of 1920x1080, however some subjects
> made minor changes like wide or ultra-wide FOV or resolution, as they recorded
> multiple sequences in their homes, and thus were switching the device off and
> on over several days. Specifically, 1% of the videos were recorded at 1280x720
> and 0.5% at 1920x1440. Also, **1% at 30fps, 1% at 48fps and 0.2% at 90fps**.

I'm wondering if all frames are extracted at 59.94 fps? Thanks.

**Comment by dimadamen** [comment]
That is correct. We re-parsed all videos to extract frames at the same rate. This is what you would get when you download the rgb frames.

**Comment by willprice** [comment]
Hi @b0ku1, The frame were actually extracted at exactly 60 FPS, you can see the details of how we extracted frames here: https://github.com/epic-kitchens/epic-kitchens-55-annotations#video-information

**Comment by b0ku1** [comment]
thanks!
